// Package backup creates and retains consistent SQLite snapshots.
package backup

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/muzaffer/internship-tracker/internal/database"
)

const filenamePrefix = "internship-tracker-"

// Config is deliberately string-based at the environment boundary so malformed
// production values can fail application startup instead of silently changing
// backup behaviour.
type Config struct {
	Enabled   string
	Directory string
	Time      string
	Timezone  string
	Retention string
}

// Service schedules one daily backup. It is disabled unless explicitly enabled.
type Service struct {
	db        *sql.DB
	enabled   bool
	directory string
	at        time.Duration
	location  *time.Location
	retention int
	logger    *slog.Logger

	startOnce sync.Once
	done      chan struct{}
}

// New validates backup configuration before the HTTP server starts. A disabled
// backup service intentionally does not create its directory or any files.
func New(db *sql.DB, cfg Config, logger *slog.Logger) (*Service, error) {
	enabled, err := strconv.ParseBool(strings.TrimSpace(cfg.Enabled))
	if err != nil {
		return nil, fmt.Errorf("BACKUP_ENABLED must be true or false: %w", err)
	}
	service := &Service{enabled: enabled, done: make(chan struct{})}
	if logger == nil {
		logger = slog.Default()
	}
	service.logger = logger
	if !enabled {
		close(service.done)
		return service, nil
	}
	if db == nil {
		return nil, errors.New("sqlite database is required when backups are enabled")
	}
	directory, err := secureDirectory(cfg.Directory)
	if err != nil {
		return nil, fmt.Errorf("BACKUP_DIRECTORY: %w", err)
	}
	at, err := parseDailyTime(cfg.Time)
	if err != nil {
		return nil, err
	}
	location, err := time.LoadLocation(strings.TrimSpace(cfg.Timezone))
	if err != nil {
		return nil, fmt.Errorf("load backup timezone %q: %w", cfg.Timezone, err)
	}
	retention, err := strconv.Atoi(strings.TrimSpace(cfg.Retention))
	if err != nil || retention < 1 {
		return nil, errors.New("BACKUP_RETENTION must be a positive integer")
	}
	service.db = db
	service.directory = directory
	service.at = at
	service.location = location
	service.retention = retention
	return service, nil
}

func parseDailyTime(value string) (time.Duration, error) {
	parsed, err := time.Parse("15:04", strings.TrimSpace(value))
	if err != nil {
		return 0, fmt.Errorf("BACKUP_TIME must be in HH:MM format: %w", err)
	}
	return time.Duration(parsed.Hour())*time.Hour + time.Duration(parsed.Minute())*time.Minute, nil
}

// Start is idempotent. Cancelling ctx stops the timer and cancels an active
// snapshot; Wait joins the scheduler during application shutdown.
func (s *Service) Start(ctx context.Context) {
	if !s.enabled {
		return
	}
	s.startOnce.Do(func() {
		go func() {
			defer close(s.done)
			s.loop(ctx)
		}()
	})
}

func (s *Service) Wait(ctx context.Context) error {
	select {
	case <-s.done:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

func (s *Service) loop(ctx context.Context) {
	for {
		next := s.next(time.Now().In(s.location))
		timer := time.NewTimer(time.Until(next))
		select {
		case <-ctx.Done():
			if !timer.Stop() {
				select {
				case <-timer.C:
				default:
				}
			}
			return
		case <-timer.C:
			result, err := s.Run(ctx)
			if err != nil {
				s.logger.Error("scheduled SQLite backup failed", "error", err)
				continue
			}
			s.logger.Info("scheduled SQLite backup completed", "path", result.Path, "created_at", result.CreatedAt)
		}
	}
}

func (s *Service) next(after time.Time) time.Time {
	hour := int(s.at / time.Hour)
	minute := int((s.at % time.Hour) / time.Minute)
	candidate := time.Date(after.Year(), after.Month(), after.Day(), hour, minute, 0, 0, s.location)
	if !candidate.After(after) {
		candidate = candidate.AddDate(0, 0, 1)
	}
	return candidate
}

type Result struct {
	Path      string
	CreatedAt time.Time
}

// Run creates a consistent snapshot in a temporary name, validates it, then
// atomically publishes it with owner-only permissions and applies retention.
func (s *Service) Run(ctx context.Context) (Result, error) {
	if !s.enabled {
		return Result{}, errors.New("SQLite backups are disabled")
	}
	result, err := Create(ctx, s.db, s.directory, time.Now().In(s.location))
	if err != nil {
		return Result{}, err
	}
	if err := s.prune(); err != nil {
		return Result{}, err
	}
	return result, nil
}

// Create creates an owner-only, transactionally consistent SQLite snapshot.
// The filename is generated by this package; callers cannot make it overwrite
// a chosen file. The snapshot is integrity-checked before it is published.
func Create(ctx context.Context, source *sql.DB, directory string, createdAt time.Time) (Result, error) {
	if source == nil {
		return Result{}, errors.New("sqlite database is required")
	}
	directory, err := secureDirectory(directory)
	if err != nil {
		return Result{}, err
	}
	nonce, err := randomSuffix()
	if err != nil {
		return Result{}, err
	}
	filename := filenamePrefix + createdAt.UTC().Format("20060102T150405.000000000Z") + "-" + nonce + ".db"
	finalPath := filepath.Join(directory, filename)
	temporaryPath := filepath.Join(directory, "."+filename+".partial")
	if _, err := os.Lstat(temporaryPath); err == nil {
		return Result{}, fmt.Errorf("temporary SQLite backup already exists: %q", temporaryPath)
	} else if !errors.Is(err, os.ErrNotExist) {
		return Result{}, fmt.Errorf("inspect temporary SQLite backup: %w", err)
	}
	defer os.Remove(temporaryPath)
	if err := database.Backup(ctx, source, temporaryPath); err != nil {
		return Result{}, err
	}
	if err := os.Chmod(temporaryPath, 0o600); err != nil {
		return Result{}, fmt.Errorf("secure temporary backup: %w", err)
	}
	if err := checkIntegrity(ctx, temporaryPath); err != nil {
		return Result{}, err
	}
	// link(2) publishes only when finalPath does not yet exist. Unlike Rename,
	// it cannot replace a concurrently-created snapshot with the same name.
	if err := os.Link(temporaryPath, finalPath); err != nil {
		return Result{}, fmt.Errorf("publish SQLite backup without overwrite: %w", err)
	}
	if err := os.Remove(temporaryPath); err != nil {
		return Result{}, fmt.Errorf("remove published temporary SQLite backup: %w", err)
	}
	return Result{Path: finalPath, CreatedAt: createdAt}, nil
}

// Verify performs a non-mutating restore preflight. It opens only the snapshot
// through a SQLite mode=ro, immutable URI, runs integrity_check, and confirms
// all migrations bundled with the selected release are recorded in it.
func Verify(ctx context.Context, path string, migrations fs.FS) error {
	names, err := database.MigrationNames(migrations)
	if err != nil {
		return fmt.Errorf("load expected migrations: %w", err)
	}
	db, err := openReadOnly(path)
	if err != nil {
		return err
	}
	defer db.Close()
	if err := checkIntegrityDB(ctx, db); err != nil {
		return err
	}
	rows, err := db.QueryContext(ctx, "SELECT name FROM schema_migrations")
	if err != nil {
		return fmt.Errorf("query snapshot migrations: %w", err)
	}
	defer rows.Close()
	applied := make(map[string]struct{}, len(names))
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return fmt.Errorf("scan snapshot migration: %w", err)
		}
		applied[name] = struct{}{}
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("read snapshot migrations: %w", err)
	}
	for _, name := range names {
		if _, ok := applied[name]; !ok {
			return fmt.Errorf("snapshot is missing migration %q", name)
		}
	}
	return nil
}

// OpenSource opens an already existing SQLite database for a VACUUM INTO
// snapshot. mode=rw prevents a typo from creating an empty production file.
func OpenSource(path string) (*sql.DB, error) {
	path, err := existingRegularPath(path)
	if err != nil {
		return nil, err
	}
	db, err := sql.Open("sqlite", fileURI(path, "rw"))
	if err != nil {
		return nil, fmt.Errorf("open SQLite source: %w", err)
	}
	db.SetMaxOpenConns(1)
	if err := db.Ping(); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("ping SQLite source: %w", err)
	}
	return db, nil
}

func checkIntegrity(ctx context.Context, path string) error {
	db, err := openReadOnly(path)
	if err != nil {
		return err
	}
	defer db.Close()
	return checkIntegrityDB(ctx, db)
}

func checkIntegrityDB(ctx context.Context, db *sql.DB) error {
	var result string
	if err := db.QueryRowContext(ctx, "PRAGMA integrity_check").Scan(&result); err != nil {
		return fmt.Errorf("run SQLite snapshot integrity check: %w", err)
	}
	if result != "ok" {
		return fmt.Errorf("SQLite snapshot integrity check failed: %s", result)
	}
	return nil
}

func secureDirectory(directory string) (string, error) {
	if strings.TrimSpace(directory) == "" {
		return "", errors.New("backup directory is required")
	}
	abs, err := filepath.Abs(directory)
	if err != nil {
		return "", fmt.Errorf("resolve backup directory: %w", err)
	}
	if err := os.MkdirAll(abs, 0o700); err != nil {
		return "", fmt.Errorf("create backup directory: %w", err)
	}
	info, err := os.Lstat(abs)
	if err != nil {
		return "", fmt.Errorf("inspect backup directory: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return "", fmt.Errorf("backup directory %q is not a directory", abs)
	}
	if err := os.Chmod(abs, 0o700); err != nil {
		return "", fmt.Errorf("secure backup directory: %w", err)
	}
	return abs, nil
}

func randomSuffix() (string, error) {
	bytes := make([]byte, 8)
	if _, err := rand.Read(bytes); err != nil {
		return "", fmt.Errorf("generate backup filename: %w", err)
	}
	return hex.EncodeToString(bytes), nil
}

func openReadOnly(path string) (*sql.DB, error) {
	path, err := existingRegularPath(path)
	if err != nil {
		return nil, err
	}
	db, err := sql.Open("sqlite", fileURI(path, "ro")+"&immutable=1")
	if err != nil {
		return nil, fmt.Errorf("open SQLite snapshot read-only: %w", err)
	}
	db.SetMaxOpenConns(1)
	return db, nil
}

func existingRegularPath(path string) (string, error) {
	if strings.TrimSpace(path) == "" {
		return "", errors.New("SQLite path is required")
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve SQLite path: %w", err)
	}
	info, err := os.Stat(abs)
	if err != nil {
		return "", fmt.Errorf("inspect SQLite path: %w", err)
	}
	if !info.Mode().IsRegular() {
		return "", fmt.Errorf("SQLite path %q is not a regular file", abs)
	}
	return abs, nil
}

func fileURI(path, mode string) string {
	uri := url.URL{Scheme: "file", Path: path}
	query := url.Values{"mode": []string{mode}}
	uri.RawQuery = query.Encode()
	return uri.String()
}

func (s *Service) prune() error {
	entries, err := os.ReadDir(s.directory)
	if err != nil {
		return fmt.Errorf("list SQLite backups: %w", err)
	}
	backups := make([]string, 0)
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasPrefix(entry.Name(), filenamePrefix) || !strings.HasSuffix(entry.Name(), ".db") {
			continue
		}
		backups = append(backups, entry.Name())
	}
	sort.Strings(backups)
	for len(backups) > s.retention {
		path := filepath.Join(s.directory, backups[0])
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove expired SQLite backup %q: %w", path, err)
		}
		backups = backups[1:]
	}
	return nil
}
